from . import ssf_sector
from . import ssf_season
from . import ssf_discipline
from . import ssf_comp_class
from . import ssf_event
from . import ssf_competition
from . import ssf_comp_ccd
from . import ssf_result_list
from . import ssf_result
from . import ssf_entry
from . import ssf_iol_role
from . import ssf_person_sector
from . import res_partner_ext
from . import ssf_cup
from . import ssf_fis_competitor
