{
    "name":        "Clio Obit — Dödsannonsbevakning",
    "version":     "18.0.8.0.0",
    "category":    "Extra Tools",
    "summary":     "Bevakar dödsannonser mot res.partner. Flera bevakare per person via clio.obit.watch.",
    "author":      "Fredrik Arvas / Arvas International AB",
    "license":     "LGPL-3",
    "depends":     ["contacts"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/clio_obit_watch_rules.xml",
        "views/clio_obit_announcement_views.xml",
        "views/clio_obit_match_views.xml",
        "views/clio_obit_watch_views.xml",
        "views/clio_obit_gedcom_views.xml",
        "views/clio_obit_add_watch_views.xml",
        "views/res_partner_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application":  False,
}
